### ISSUE TITLE
about the pred = pred[:, -1, :]

### ISSUE THREAD

**Issue by zf223669** [ki-ljl/LSTM-Load-Forecasting#2]
Hi， I am learning your wonderful code.
Now i met a problem about the code : pred = pred[:, -1, :]
Why does just get the last column about the pred?
Could you explain in more detail to me, Thanks a lot!

**Comment by ki-ljl** [comment]
The shape of pred is (batch_size, seq_len, output_size). Suppose we use the first 24 hours (1 to 24) to predict the load for the next 2 hours (25 to 26), then seq_len=24, output_size=2. According to the principle of LSTM, the final output contains the predicted values of all positions, that is ((2 3), (3 4), (4 5)...(25 26)). Obviously we only need the last predicted value, which is pred[:, -1, :].

**Comment by zf223669** [comment]
Thank you for your reply!
