### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xinsuinizhuan** [ki-ljl/LSTM-Load-Forecasting#4]
I use my data, have two colums, one is timestamp, one is value.
And use the Multivariate-SingleStep-LSTM and Multivariate-MultiStep-LSTM, the list index out of range:

![图片](https://user-images.githubusercontent.com/40679769/164680972-9e860ab3-a477-4899-a56c-464701a34f5e.png)

**Comment by ki-ljl** [comment]
The purpose of this code is to add environment variables, which are not in your data, so you need to comment out these two lines.
